### ISSUE TITLE
All runs well, can auth with local and google but server responds with Unauthorized

### ISSUE THREAD

**Issue by nigel-dewar** [ronzeidman/ng2-ui-auth-example#2] opened 2016-07-09 15:16 UTC
Page displays 

~~~ Hello undefined ~~~

Unauthorized

console displays 

Failed to load resource: the server responded with a status of 401 (Unauthorized)

Everything runs fine, can auth to google for instance, but for some reason this is happening. Have confirmed data is saving successfully in rethinkdb also.

All modules installed correctly on npm install. So really cant see any reason why this is failing,.

If I restart the project, I can sign in, and my name appears, but I still get 401 unauthorized trying to access the helloworld route.

I log out, log back in, my name no longer appears, but still I get 401 unauthorized.

Did I miss something in the setup?

cheers

**Comment by ronzeidman** [comment] 2016-07-09 16:55
No, this is the expected behavior. The upper section uses the JwtHttp and the lower "unauthorized" uses plain Http, this is to show that the server blocks unauthorized communication and doesn't block authorized ones.
Maybe I should explain it in the read me

**Comment by ronzeidman** [comment] 2016-07-10 10:11
Fixed the issue of 'Hello **undefined**' this was caused due to the return of an array instead of a single user by the DB query of "google" route. it was fixed in the latest commit.

**Comment by nigel-dewar** [comment] 2016-07-12 21:10
Thanks very much Ron. I gotta say this is a really great thing you have done porting satellizer from angular 1 to 2. Looking through your code you have done such a sweet job.

Thank you so much for your hard work, and I love that you are using rethinkdb for storage.

**Comment by ronzeidman** [comment] 2016-07-13 06:58
Thanks :)

I've updated the readme to show the expected result.

**Closed as completed by ronzeidman** 2016-07-13 06:58 UTC

**Comment by nigel-dewar** [comment] 2016-07-14 06:57
Cheers Ron
